# Generated by Django 5.1.3 on 2024-11-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_task_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_time',
            field=models.DateTimeField(verbose_name='time published'),
        ),
    ]
